/**
 * Data-driven scene graph.
 * Drop a matching file into /public/assets/kerala-temple/... and the engine
 * picks it up. Tune composition here — never inside the renderer.
 *
 * Units:
 *   depth     0 (against the lens) → 1000 (horizon)
 *   parallax  extra XY drift vs camera / pointer
 *   x, y      viewport-normalized offsets at that depth (−1 … 1)
 *   scale     multiplier on the frustum-fitted plane
 *   fit       cover | height | width | band  (object-fit)
 *   pinX/Y    0 = left/bottom, 1 = right/top  (object-position)
 *   wide/tall optional overrides when the viewport is landscape / portrait
 *   content*  crop box of the painted subject (0–1) so pins use the building, not empty sky
 */

/**
 * Walk stack, front → back:
 * RANGAM grove → pond → gopuram → inner yard
 */
export const liveLayerIds = [
  "rangam-grove",
  "temple-pond",
  "gopuram",
  "kathakali-troupe",
  "inner-yard",
];

export const sceneLayers = [
  {
    id: "moon",
    src: "/assets/kerala-temple/background/moon.webp?v=3",
    depth: 920,
    parallax: 0.02,
    scale: 1,
    x: 0,
    y: 0,
    tint: "#e8e4d4",
  },
  {
    id: "western-ghats",
    src: "/assets/kerala-temple/background/western-ghats.webp?v=3",
    depth: 800,
    parallax: 0.03,
    scale: 1,
    x: 0,
    y: 0,
    fit: "cover",
    pinX: 0.5,
    pinY: 0,
    contentTop: 0.34,
    contentBottom: 0.86,
    ground: true,
    tint: "#1a3344",
    appear: { in: 0, out: 0.8 },
  },
  {
    id: "distant-vegetation",
    src: "/assets/kerala-temple/background/distant-vegetation.webp?v=3",
    depth: 90,
    parallax: 0.75,
    scale: 1,
    x: 0,
    y: 0,
    fit: "cover",
    pinX: 0.32,
    pinY: 0,
    tint: "#0d2a24",
    passThrough: true,
    walk: {
      scale: [1.18, 0.62],
      x: [0.02, 0],
      y: [0, -0.08],
      opacity: [1, 0],
    },
  },
  {
    id: "nalambalam",
    src: "/assets/kerala-temple/architecture/nalambalam.webp?v=3",
    depth: 540,
    parallax: 0.08,
    scale: 1,
    x: 0,
    y: 0,
    fit: "width",
    pinX: 0.5,
    pinY: 0.4,
    contentTop: 0.25,
    contentBottom: 0.72,
    tint: "#2e2218",
    appear: { in: 0.26, out: 1 },
    aim: { u: 0.5, v: 0.56 },
  },
  {
    id: "rangam-grove",
    src: "/assets/kerala-temple/foreground/rangam-grove-hq.webp?v=2",
    depth: 36,
    worldZ: 3.4,
    parallax: 0,
    scale: 1,
    x: 0,
    y: 0,
    fit: "width",
    pinX: 0.5,
    pinY: 0,
    contentTop: 0,
    contentBottom: 1,
    ground: true,
    hero: true,
    passThrough: true,
    wide: { scale: 1 },
    tall: { scale: 1 },
  },
  {
    id: "temple-pond",
    src: "/assets/kerala-temple/foreground/temple-pond.webp?v=6",
    depth: 388,
    parallax: 0.1,
    scale: 1.08,
    x: 0,
    y: 0,
    fit: "width",
    pinX: 0.5,
    pinY: 0,
    contentTop: 0.252,
    contentBottom: 1,
    anchorTop: 0.6,
    tint: "#1c2a32",
    passThrough: true,
    passLead: 11,
    aim: { u: 0.5, v: 0.9 },
    walk: { y: [0, -0.1], in: 0.1, out: 0.46 },
    wide: {
      y: 0.1,
      walk: { y: [0, -0.18], in: 0.04, out: 0.38 },
    },
    tall: {
      y: 0,
      walk: { y: [0, -0.05], in: 0.16, out: 0.48 },
    },
  },
  {
    id: "gopuram",
    src: "/assets/kerala-temple/architecture/gopuram-hq.webp?v=29",
    depth: 420,
    parallax: 0.06,
    scale: 1.12,
    x: 0,
    y: 1.1,
    fit: "width",
    pinX: 0.5,
    pinY: 0,
    contentTop: 0.184,
    contentBottom: 0.907,
    ground: true,
    tint: "#3d2a1a",
    opaque: true,
    passThrough: true,
    aim: { u: 0.5, v: 0.75 },
    doorHole: { u: [0.466, 0.534], v: [0.652, 0.852] },
    wide: { fit: "height", scale: 0.58 },
    tall: { scale: 1.18 },
  },
  {
    id: "inner-yard-left",
    src: "/assets/kerala-temple/architecture/inner-yard-left.webp?v=8",
    depth: 428,
    parallax: 0.06,
    scale: 0.36,
    x: -0.34,
    y: 1.18,
    fit: "height",
    pinX: 0.22,
    pinY: 0,
    contentTop: 0.06,
    contentBottom: 1,
    ground: true,
    tint: "#2a2018",
    opaque: true,
    passThrough: true,
    wide: { scale: 0.42, x: -0.48, pinX: 0.18 },
  },
  {
    id: "inner-yard-right",
    src: "/assets/kerala-temple/architecture/inner-yard-right.webp?v=8",
    depth: 428,
    parallax: 0.06,
    scale: 0.36,
    x: 0.34,
    y: 1.18,
    fit: "height",
    pinX: 0.78,
    pinY: 0,
    contentTop: 0.06,
    contentBottom: 1,
    ground: true,
    tint: "#2a2018",
    opaque: true,
    passThrough: true,
    wide: { scale: 0.42, x: 0.48, pinX: 0.82 },
  },
  {
    id: "inner-yard",
    src: "/assets/kerala-temple/architecture/inner-yard-hq.webp?v=11",
    // Sit just behind the gopuram so the door sill meets the courtyard floor.
    depth: 505,
    parallax: 0,
    scale: 0.28,
    x: 0,
    y: 0.22,
    fit: "width",
    pinX: 0.5,
    pinY: 0.5,
    contentTop: 0.12,
    contentBottom: 1,
    tint: "#1a1410",
    opaque: true,
    aim: { u: 0.5, v: 0.52 },
    wide: {
      scale: 0.28,
      y: 0.22,
    },
    tall: {
      scale: 0.5,
      y: 0.16,
    },
  },
  {
    id: "kathakali-troupe",
    src: "/assets/kerala-temple/characters/kathakali-troupe-hq.webp?v=2",
    // Looping performance: colour in the top half of each frame, its cut-out matte in the
    // bottom half (see videoPlate in engine.js). Replaces the still once it can play.
    video: "/assets/kerala-temple/characters/kathakali-troupe.mp4?v=7",
    videoAspect: 1024 / 500,
    depth: 678,
    parallax: 0,
    scale: 1,
    x: 0,
    y: 0,
    fit: "width",
    pinX: 0.5,
    pinY: 0.5,
    opaque: true,
    depthTest: true,
    attach: {
      id: "inner-yard",
      u: 0.5,
      v: 0.96,
      pinV: 0.978,
      width: 0.66,
    },
  },
  {
    id: "courtyard-floor",
    src: "/assets/kerala-temple/architecture/courtyard-floor.webp?v=3",
    depth: 500,
    parallax: 0.1,
    scale: 1,
    x: 0,
    y: 0,
    fit: "cover",
    pinX: 0.5,
    pinY: 0,
    ground: true,
    tint: "#24180f",
    appear: { in: 0, out: 1 },
    walk: {
      scale: [0.9, 1.2],
      opacity: [1, 1],
    },
  },
  {
    id: "doorway",
    src: "/assets/kerala-temple/architecture/doorway.webp",
    depth: 370,
    parallax: 0.27,
    scale: 0.42,
    x: 0.18,
    y: -0.04,
    tint: "#4a3018",
    appear: { in: 0.18, out: 1 },
  },
  {
    id: "lamps-background",
    src: "/assets/kerala-temple/atmosphere/lamp-glow.webp",
    depth: 350,
    parallax: 0.28,
    scale: 0.55,
    x: -0.22,
    y: -0.12,
    tint: "#e8a030",
    appear: { in: 0.12, out: 1 },
  },

  // — musicians, seated behind the dancers —
  {
    id: "vocalist-ponnani",
    src: "/assets/kerala-temple/musicians/vocalist-ponnani.webp",
    depth: 320,
    parallax: 0.33,
    scale: 0.22,
    x: -0.28,
    y: -0.16,
    tint: "#4a3a28",
    appear: { in: 0.28, out: 1 },
  },
  {
    id: "vocalist-shinkiti",
    src: "/assets/kerala-temple/musicians/vocalist-shinkiti.webp",
    depth: 315,
    parallax: 0.34,
    scale: 0.2,
    x: -0.18,
    y: -0.15,
    tint: "#453626",
    appear: { in: 0.3, out: 1 },
  },
  {
    id: "chenda",
    src: "/assets/kerala-temple/musicians/chenda.webp",
    depth: 300,
    parallax: 0.35,
    scale: 0.24,
    x: 0.26,
    y: -0.18,
    tint: "#3f3224",
    appear: { in: 0.32, out: 1 },
  },
  {
    id: "maddalam",
    src: "/assets/kerala-temple/musicians/maddalam.webp",
    depth: 298,
    parallax: 0.36,
    scale: 0.22,
    x: 0.36,
    y: -0.2,
    tint: "#3a2e22",
    appear: { in: 0.34, out: 1 },
  },
  {
    id: "chengila",
    src: "/assets/kerala-temple/musicians/chengila.webp",
    depth: 296,
    parallax: 0.36,
    scale: 0.16,
    x: 0.16,
    y: -0.17,
    tint: "#4a3a28",
    appear: { in: 0.36, out: 1 },
  },
  {
    id: "ilathalam",
    src: "/assets/kerala-temple/musicians/ilathalam.webp",
    depth: 294,
    parallax: 0.37,
    scale: 0.15,
    x: 0.08,
    y: -0.16,
    tint: "#4a3a28",
    appear: { in: 0.36, out: 1 },
  },
  {
    id: "idakka",
    src: "/assets/kerala-temple/musicians/idakka.webp",
    depth: 292,
    parallax: 0.37,
    scale: 0.17,
    x: -0.06,
    y: -0.18,
    tint: "#403226",
    appear: { in: 0.38, out: 1 },
  },

  // — Kathakali, each on their own plane —
  {
    id: "sita",
    src: "/assets/kerala-temple/characters/sita-minukku.webp",
    depth: 240,
    parallax: 0.42,
    scale: 0.34,
    x: 0.02,
    y: -0.12,
    tint: "#c47a2c",
    appear: { in: 0.42, out: 1 },
  },
  {
    id: "rama",
    src: "/assets/kerala-temple/characters/rama-pacha.webp",
    depth: 200,
    parallax: 0.55,
    scale: 0.4,
    x: -0.12,
    y: -0.1,
    tint: "#1a6b4a",
    appear: { in: 0.4, out: 1 },
  },
  {
    id: "kari",
    src: "/assets/kerala-temple/characters/kari.webp",
    depth: 210,
    parallax: 0.48,
    scale: 0.26,
    x: 0.3,
    y: -0.14,
    tint: "#1a1a1c",
    appear: { in: 0.48, out: 1 },
    hideBelow: 720,
  },
  {
    id: "chuvanna-thadi",
    src: "/assets/kerala-temple/characters/chuvanna-thadi.webp",
    depth: 190,
    parallax: 0.52,
    scale: 0.3,
    x: -0.34,
    y: -0.08,
    tint: "#7a1c24",
    appear: { in: 0.5, out: 1 },
    hideBelow: 900,
  },
  {
    id: "ravana",
    src: "/assets/kerala-temple/characters/ravana-kathi.webp",
    depth: 170,
    parallax: 0.6,
    scale: 0.46,
    x: 0.2,
    y: -0.08,
    tint: "#8b1a2b",
    appear: { in: 0.46, out: 1 },
  },
  {
    id: "hanuman",
    src: "/assets/kerala-temple/characters/hanuman-vella-thadi.webp",
    depth: 150,
    parallax: 0.68,
    scale: 0.38,
    x: -0.28,
    y: -0.18,
    tint: "#d4cfc4",
    appear: { in: 0.52, out: 1 },
  },

  // — near architecture —
  {
    id: "pillar-left",
    src: "/assets/kerala-temple/architecture/pillar-left.webp",
    depth: 120,
    parallax: 0.75,
    scale: 0.62,
    x: -0.62,
    y: 0.02,
    tint: "#5c4030",
    appear: { in: 0.2, out: 1 },
  },
  {
    id: "pillar-right",
    src: "/assets/kerala-temple/architecture/pillar-right.webp",
    depth: 115,
    parallax: 0.76,
    scale: 0.58,
    x: 0.66,
    y: 0,
    tint: "#5c4030",
    appear: { in: 0.22, out: 1 },
    hideBelow: 720,
  },

  // — very near —
  {
    id: "foreground-lamp-left",
    src: "/assets/kerala-temple/foreground/foreground-lamp-left.webp",
    depth: 80,
    parallax: 0.9,
    scale: 0.42,
    x: -0.58,
    y: -0.22,
    tint: "#e8a030",
    appear: { in: 0.15, out: 1 },
  },
  {
    id: "foreground-lamp-right",
    src: "/assets/kerala-temple/foreground/foreground-lamp-right.webp",
    depth: 74,
    parallax: 0.92,
    scale: 0.36,
    x: 0.6,
    y: -0.18,
    tint: "#e8a030",
    appear: { in: 0.18, out: 1 },
    hideBelow: 720,
  },
  {
    id: "banana-leaves",
    src: "/assets/kerala-temple/foreground/banana-leaves.webp",
    depth: 50,
    parallax: 1,
    scale: 0.7,
    x: -0.72,
    y: 0.18,
    tint: "#0f3d28",
  },
  {
    id: "coconut-leaves",
    src: "/assets/kerala-temple/foreground/coconut-leaves.webp",
    depth: 46,
    parallax: 1.05,
    scale: 0.64,
    x: 0.74,
    y: 0.22,
    tint: "#12422c",
    hideBelow: 640,
  },
  {
    id: "incense-smoke",
    src: "/assets/kerala-temple/atmosphere/incense-smoke.webp",
    depth: 36,
    parallax: 0.7,
    scale: 0.5,
    x: -0.1,
    y: 0.06,
    tint: "#8a8a92",
    appear: { in: 0.35, out: 1 },
  },
  {
    id: "petals",
    src: "/assets/kerala-temple/atmosphere/petals.webp",
    depth: 28,
    parallax: 1.08,
    scale: 0.55,
    x: 0.08,
    y: 0.12,
    tint: "#c45a4a",
    appear: { in: 0.55, out: 1 },
    hideBelow: 720,
  },
  {
    id: "hanging-leaves",
    src: "/assets/kerala-temple/atmosphere/particles.webp",
    depth: 20,
    parallax: 1.15,
    scale: 0.8,
    x: 0.04,
    y: 0.42,
    tint: "#0a2e1c",
  },
];

export const phases = [
  { id: "approach", from: 0, to: 0.25, label: "01  Approach", malayalam: "വഴി" },
  { id: "emerge", from: 0.25, to: 0.5, label: "02  Gopuram", malayalam: "ഗോപുരം" },
  { id: "enter", from: 0.5, to: 0.75, label: "03  Courtyard", malayalam: "മുറ്റം" },
  { id: "performance", from: 0.75, to: 1, label: "04  Rangam", malayalam: "രംഗം" },
];
